-- 코드를 입력하세요
SELECT a.AUTHOR_ID, b.AUTHOR_NAME, a.CATEGORY, sum(c.SALES*a.PRICE) AS TOTAL_SALES FROM BOOK as a
    JOIN AUTHOR as b ON a.AUTHOR_ID = b.AUTHOR_ID
    JOIN (SELECT BOOK_ID, sum(SALES) as SALES FROM BOOK_SALES WHERE YEAR(SALES_DATE) = 2022 and MONTH(SALES_DATE) = 1 GROUP BY BOOK_ID) as c ON a.BOOK_ID = c.BOOK_ID
    GROUP BY AUTHOR_ID, CATEGORY
    ORDER BY AUTHOR_ID, CATEGORY desc